#define VIAL_KEYBOARD_UID {0x9C, 0xAD, 0x26, 0x0E, 0x3A, 0xFF, 0x0D, 0x10}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define VIAL_TAP_DANCE_ENTRIES 16
#define VIAL_COMBO_ENTRIES 69

#define DYNAMIC_KEYMAP_LAYER_COUNT 16
