#!/usr/bin/env bash
set -euo pipefail
#MISE description="Reset a keyboard's firmware in QMK_HOME (only for keyboards with custom firmware)"
#MISE usage="reset <keyboard>"
#MISE arg="keyboard"


kb="$1"

mise run remove "$kb"

echo "Syncing..."
mise run sync "$kb"
