#!/usr/bin/env bash
#MISE description="Reset a keyboard's firmware in QMK_HOME (only for keyboards with custom firmware)"
#USAGE arg "<keyboard>"
set -euo pipefail

kb="$1"

mise run remove "$kb"

echo "Syncing..."
mise run sync "$kb"
